// <auto-generated />
using System;
using LicenseManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseManager.Infrastructure.Migrations;

/// <summary>
/// Designer-generated companion to <see cref="Phase4C_Payments"/>. Captures
/// the model state EF should compare against when the next migration is
/// generated. See <see cref="ApplicationDbContextModelSnapshot"/> for a
/// detailed note on the deliberate scope of this snapshot.
/// </summary>
[DbContext(typeof(ApplicationDbContext))]
[Migration("20260522120000_Phase4C_Payments")]
partial class Phase4C_Payments
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        ApplicationDbContextModelSnapshot.BuildPaymentsModel(modelBuilder);
#pragma warning restore 612, 618
    }
}
