// <auto-generated />
using System;
using LicenseManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseManager.Infrastructure.Migrations;

/// <summary>
/// Compile-time snapshot of the EF model. Used by <c>dotnet ef migrations
/// add</c> to compute the diff for the next migration.
///
/// SCOPE:
/// =====
/// This snapshot intentionally describes ONLY the three Phase 4C entities
/// (Payment, Refund, WebhookEvent). The other twenty entities in the model
/// (AdminUser, License, Customer, Product, ...) were created by the hand-
/// authored SQL migrations in <c>database/migrations/001_initial_schema.sql</c>
/// and friends, and have never been managed through the EF migration
/// pipeline.
///
/// CONSEQUENCES:
/// =============
///   * <c>dotnet ef database update</c> works correctly - it only consults
///     the migration files (Up/Down), not this snapshot. Both fresh and
///     existing databases get the three new tables applied as expected.
///
///   * <c>dotnet ef migrations add SomeNewMigration</c> will mis-diff: it
///     will see twenty entities in the model that are absent from this
///     snapshot and will emit a migration full of <c>CREATE TABLE</c>
///     statements for tables that already exist. **Do not commit such a
///     migration as-is.**
///
/// HOW TO ADOPT EF MIGRATIONS PROPERLY (future task, out of scope for B-1):
/// =======================================================================
///   1. Reconcile the existing twenty-entity model with the SQL schema
///      (e.g. add HasMaxLength / Ignore for Dictionary&lt;string,object&gt;
///      properties that have no DB column).
///   2. Run <c>dotnet ef migrations add 0_BaselineExisting --output-dir
///      Migrations</c> with an empty <c>Up</c>/<c>Down</c> body.
///   3. Insert a row into <c>__EFMigrationsHistory</c> for that baseline on
///      every existing database so EF treats it as already applied.
///   4. From that point on, every model change can be authored via
///      <c>dotnet ef migrations add</c>.
/// </summary>
[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    /// <inheritdoc />
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        BuildPaymentsModel(modelBuilder);
#pragma warning restore 612, 618
    }

    /// <summary>
    /// Shared between <see cref="BuildModel"/> and the Phase4C designer's
    /// <c>BuildTargetModel</c> so both stay in lockstep.
    /// </summary>
    internal static void BuildPaymentsModel(ModelBuilder modelBuilder)
    {
        // -------------------------------------------------------------
        // Payment
        // -------------------------------------------------------------
        modelBuilder.Entity("LicenseManager.Domain.Entities.Payment", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uuid")
                .HasColumnName("customer_id");

            b.Property<Guid?>("LicenseId")
                .HasColumnType("uuid")
                .HasColumnName("license_id");

            b.Property<int>("Provider")
                .HasColumnType("integer")
                .HasColumnName("provider");

            b.Property<string>("ProviderPaymentId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("provider_payment_id");

            b.Property<string>("ProviderOrderId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("provider_order_id");

            b.Property<string>("ProviderCustomerId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("provider_customer_id");

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)")
                .HasColumnName("amount");

            b.Property<long>("AmountMinor")
                .HasColumnType("bigint")
                .HasColumnName("amount_minor");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("character varying(3)")
                .HasColumnName("currency");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<DateTime?>("AuthorizedAt").HasColumnType("timestamp without time zone").HasColumnName("authorized_at");
            b.Property<DateTime?>("CapturedAt"  ).HasColumnType("timestamp without time zone").HasColumnName("captured_at");
            b.Property<DateTime?>("FailedAt"    ).HasColumnType("timestamp without time zone").HasColumnName("failed_at");
            b.Property<DateTime?>("CancelledAt" ).HasColumnType("timestamp without time zone").HasColumnName("cancelled_at");

            b.Property<long>("RefundedAmountMinor")
                .HasColumnType("bigint")
                .HasDefaultValue(0L)
                .HasColumnName("refunded_amount_minor");

            b.Property<string>("ClientSecret").HasMaxLength(512 ).HasColumnType("character varying(512)" ).HasColumnName("client_secret");
            b.Property<string>("CheckoutUrl" ).HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("checkout_url");
            b.Property<string>("Receipt"     ).HasMaxLength(64  ).HasColumnType("character varying(64)"  ).HasColumnName("receipt");
            b.Property<string>("Description" ).HasMaxLength(512 ).HasColumnType("character varying(512)" ).HasColumnName("description");
            b.Property<string>("ErrorCode"   ).HasMaxLength(128 ).HasColumnType("character varying(128)" ).HasColumnName("error_code");
            b.Property<string>("ErrorMessage").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("error_message");

            b.Property<string>("RawProviderData").HasColumnType("text").HasColumnName("raw_provider_data");
            b.Property<string>("Metadata"       ).HasColumnType("jsonb").HasColumnName("metadata");

            // BaseEntity audit fields
            b.Property<DateTime>("CreatedAt" ).HasColumnType("timestamp without time zone").HasDefaultValueSql("now()").HasColumnName("created_at");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp without time zone").HasColumnName("updated_at");
            b.Property<string>("CreatedBy"   ).HasColumnType("text").HasColumnName("created_by");
            b.Property<string>("UpdatedBy"   ).HasColumnType("text").HasColumnName("updated_by");
            b.Property<bool>("IsDeleted"     ).HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_deleted");
            b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp without time zone").HasColumnName("deleted_at");

            b.HasKey("Id");

            b.HasIndex("Provider", "ProviderPaymentId").HasDatabaseName("ix_payments_provider_provider_payment_id");
            b.HasIndex("Provider", "ProviderOrderId"  ).HasDatabaseName("ix_payments_provider_provider_order_id");
            b.HasIndex("CustomerId").HasDatabaseName("ix_payments_customer_id");
            b.HasIndex("LicenseId" ).HasDatabaseName("ix_payments_license_id");
            b.HasIndex("Status"    ).HasDatabaseName("ix_payments_status");
            b.HasIndex("CreatedAt" ).HasDatabaseName("ix_payments_created_at");

            b.ToTable("payments", (string)null);
        });

        // -------------------------------------------------------------
        // Refund
        // -------------------------------------------------------------
        modelBuilder.Entity("LicenseManager.Domain.Entities.Refund", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid>("PaymentId")
                .HasColumnType("uuid")
                .HasColumnName("payment_id");

            b.Property<string>("ProviderRefundId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("provider_refund_id");

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)")
                .HasColumnName("amount");

            b.Property<long>("AmountMinor")
                .HasColumnType("bigint")
                .HasColumnName("amount_minor");

            b.Property<string>("Currency")
                .IsRequired()
                .HasMaxLength(3)
                .HasColumnType("character varying(3)")
                .HasColumnName("currency");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<string>("Reason"      ).HasMaxLength(256 ).HasColumnType("character varying(256)" ).HasColumnName("reason");
            b.Property<string>("ErrorMessage").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("error_message");
            b.Property<DateTime?>("RefundedAt").HasColumnType("timestamp without time zone").HasColumnName("refunded_at");
            b.Property<string>("RawProviderData").HasColumnType("text").HasColumnName("raw_provider_data");

            // BaseEntity
            b.Property<DateTime>("CreatedAt" ).HasColumnType("timestamp without time zone").HasDefaultValueSql("now()").HasColumnName("created_at");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp without time zone").HasColumnName("updated_at");
            b.Property<string>("CreatedBy"   ).HasColumnType("text").HasColumnName("created_by");
            b.Property<string>("UpdatedBy"   ).HasColumnType("text").HasColumnName("updated_by");
            b.Property<bool>("IsDeleted"     ).HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_deleted");
            b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp without time zone").HasColumnName("deleted_at");

            b.HasKey("Id");

            b.HasIndex("PaymentId"       ).HasDatabaseName("ix_refunds_payment_id");
            b.HasIndex("ProviderRefundId").HasDatabaseName("ix_refunds_provider_refund_id");
            b.HasIndex("Status"          ).HasDatabaseName("ix_refunds_status");

            b.ToTable("refunds", (string)null);
        });

        // -------------------------------------------------------------
        // WebhookEvent
        // -------------------------------------------------------------
        modelBuilder.Entity("LicenseManager.Domain.Entities.WebhookEvent", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<int>("Provider")
                .HasColumnType("integer")
                .HasColumnName("provider");

            b.Property<string>("ProviderEventId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("provider_event_id");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("event_type");

            b.Property<int>("Status")
                .HasColumnType("integer")
                .HasColumnName("status");

            b.Property<string>("Payload")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("payload");

            b.Property<string>("Signature").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("signature");

            b.Property<DateTime>("ReceivedAt")
                .HasColumnType("timestamp without time zone")
                .HasDefaultValueSql("now()")
                .HasColumnName("received_at");

            b.Property<DateTime?>("ProcessedAt").HasColumnType("timestamp without time zone").HasColumnName("processed_at");
            b.Property<string>("ErrorMessage" ).HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("error_message");
            b.Property<Guid?>("PaymentId"     ).HasColumnType("uuid").HasColumnName("payment_id");

            // BaseEntity
            b.Property<DateTime>("CreatedAt" ).HasColumnType("timestamp without time zone").HasDefaultValueSql("now()").HasColumnName("created_at");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp without time zone").HasColumnName("updated_at");
            b.Property<string>("CreatedBy"   ).HasColumnType("text").HasColumnName("created_by");
            b.Property<string>("UpdatedBy"   ).HasColumnType("text").HasColumnName("updated_by");
            b.Property<bool>("IsDeleted"     ).HasColumnType("boolean").HasDefaultValue(false).HasColumnName("is_deleted");
            b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp without time zone").HasColumnName("deleted_at");

            b.HasKey("Id");

            b.HasIndex("Provider", "ProviderEventId")
                .IsUnique()
                .HasDatabaseName("ix_webhook_events_provider_provider_event_id");

            b.HasIndex("Status"     ).HasDatabaseName("ix_webhook_events_status");
            b.HasIndex("ReceivedAt" ).HasDatabaseName("ix_webhook_events_received_at");
            b.HasIndex("PaymentId"  ).HasDatabaseName("ix_webhook_events_payment_id");

            b.ToTable("webhook_events", (string)null);
        });
    }
}
