apiVersion: v1
kind: ConfigMap
metadata:
  name: licensemanager-config
  namespace: licensemanager
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "LicenseManagerAPI"
  Jwt__Audience: "LicenseManagerClient"
  Jwt__ExpiryMinutes: "60"
